### ISSUE TITLE
Flathub Screenshots are of Evince, Not Papers

### ISSUE THREAD

**Issue by cameronbosch** [flathub/org.gnome.Papers#2]
I was looking at the screenshots for Papers and they look exactly like Evince, not Papers (this app). I can confirm after running the app that this is indeed the case. Could somebody fix the app screenshots on the Flathub page?

**Comment by pabloyoyoista** [comment]
I pushed [46.2](https://download.gnome.org/sources/papers/46/) with the updated screenshots. I'm waiting to see if flathub can pick the new version and create a pull request for me, and then this should be fixed :D Thanks for creating this bug report :)
