### ISSUE TITLE
Can't open on wayland after updated to 47

### ISSUE THREAD

**Issue by lumingzh** [flathub/org.gnome.Papers#6]
All gnome apps run on org.gnome.Platform//47 can't open on wayland after updated to 47, include papers, showtime, extensions.... They can only open on X11.

**Comment by lumingzh** [comment]
The error tip: `Gdk-Message: 07:14:23.426: Error 71 (协议错误) dispatching to Wayland display`

**Comment by lumingzh** [comment]
BTW the host gnome version is 46 on fedora silverblue 40.

**Comment by pabloyoyoista** [comment]
Thanks a lot for the report

> All gnome apps run on org.gnome.Platform//47 can't open on wayland after updated to 47, include papers, showtime, extensions.... They can only open on X11.

For this exact reason, please discuss this with the Release Team (possibly comment in gnome-build-meta repository, or matrix). There's nothing we can do as app developers to fix it
